### ISSUE TITLE
Improved activation flow

### ISSUE THREAD

**Issue by nblackburn** [BlythMeister/Gallifrey#257]
Improve the activation flow for activating the premium features so you can just enter the email address used for the donation to unlock the additional features.

See https://www.heidisql.com for a reference of a working example of this system.

**Comment by BlythMeister** [comment]
Hi,

Since the donation unlock also works on an entire Jira domain, this method won't work for my use case.

This method also means i need to store your email address in a decryptable format.
The method i have chose to unlock premium has security at the heart.

The file itself is encrypted with a private string
The data for checking is a 1 way hash of data from your installed instance so is not traceable or decryptable.

The file itself contains just the one way hash and the paypal donation id (again, no personally identifiable information).

Finally, all of this can be done using static files rather than me having to pay to host some executable code somewhere.  All the executable code runs locally to you.

I will typically unlock the premium features within 0-3 hours of the donation.

**Comment by nblackburn** [comment]
OK so that system might not fit your use case but the flow could still be improved by automating the process rather than it being manual.

Being as you request the installation id on the form, this should easily be possible means you don't need to worry about fufiling orders within a given time period.

**Comment by BlythMeister** [comment]
@nblackburn that would mean i need to host a service somewhere linked to my paypal account...
